### ISSUE TITLE
Zero in coordinate parameter

### ISSUE THREAD

**Issue by lbuchs** [winds-mobi/winds-mobi-api#31]
the api does not respect a coordinate if the value is 0 degree:

Example: 
https://winds.mobi/api/2.2/stations/?limit=500&keys=pv-id&keys=pv-code&keys=pv-name&keys=short&keys=name&keys=alt&keys=peak&keys=status&keys=tz&keys=loc&keys=url&keys=last._id&keys=last.w-dir&keys=last.w-avg&keys=last.w-max&keys=last.temp&keys=last.hum&keys=last.rain&keys=last.pres&within-pt1-lat=49&within-pt1-lon=0&within-pt2-lat=50&within-pt2-lon=1&last-measure=4000

in this case, `within-pt1-lon=0` is ignored.

Thanks for your work!
Lukas

**Comment by ysavary** [comment]
Nice catch @lbuchs 👍 The PR #34 is deployed to https://winds.mobi/api/2.3/
